before_install:
- "sudo apt-get install --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra texlive-latex-recommended dvipng texlive-tipa"
- travis_wait 20
script:
- pdflatex modern-gaulish-lessons/modern-gaulish-lessons.tex
- pdflatex modern-gaulish-lessons/modern-gaulish-lessons.tex